### ISSUE TITLE
Add Biolink Model validation depth to Edge attribute validation

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATSTranslator/reasoner-validator#19]
The current TRAPI Knowledge Graph edge validation falls short of detailed validation of edge attributes (see [attribute validation code snippet (or lack thereof) in the edge validator](https://github.com/NCATSTranslator/reasoner-validator/blob/master/reasoner_validator/biolink/__init__.py#L295)).  

Deeper validation of Biolink Model (and perhaps, some TRAPI-specific) validation is required at this level.

**Comment by RichardBruskiewich** [comment]
Commentary from @edeutsch specifically regarding validation of the `attribute_type_id` (preferably inheriting from `biolink:association_slot`)

_The constraint is not really absolute, mostly because many of the concepts we want to convey are not in biolink. So I think we should enforce a curie, so if there's not colon, then that should be an error. If the prefix is not biolink, that should be a warning. If the prefix is not known to biolink that should be a double warning. Are we able to report warnings? or just errors?_
- _ERROR if not a CURIE_
- _WARNING if not an instance of `biolink:association_slot` (but is another Biolink class?)_
- _(double) WARNING if prefix is not known to Biolink (i.e. not known to Biolink in what context? All registered prefixes?)_
_

**Comment by sierra-moxon** [comment]
toolkit.get_element_by_prefix()  might help
if that returned an empty set, you'd know that biolink doesn't register the prefix on any of its classes.

If the double warning is instead to validate that the curie prefix is a valid prefix in the world, I think you can use other packages for that (see bioregistry). 

For infores validation, I'd like to add BMT methods that would query that controlled vocabulary.  We could repurpose this ticket for that purpose, if you think toolkit.get_element_by_prefix() will work for this.

**Comment by RichardBruskiewich** [comment]
Yes, `toolkit.get_element_by_prefix()` will suffice. I've added it with unit tests.

**Comment by RichardBruskiewich** [comment]
Substantially resolved by PR https://github.com/NCATSTranslator/reasoner-validator/pull/31.

The one missing aspect of this issue to be implemented is the ERROR / WARNING / (double) WARNING classification above. This intent is covered by PR https://github.com/NCATSTranslator/reasoner-validator/issues/27.

**Comment by RichardBruskiewich** [comment]
@sierra-moxon , @edeutsch , rather than opening up a fresh issue, I note our discussion today (23 March 2023) as discovering that `toolkit.get_element_by_prefix()` is limited to searches on category class `id_prefix` values and rather that the use case requires that we cast a wider net, perhaps including association slots.  In the meantime, it almost feels like we need to revisit the Biolink model for `biolink:Attribute` (which has some relevant but not all id_prefix mappings), and its relationship to `biolink:has_attribute_type`, etc. as well as internal 'attribute types' like `biolink:knowledge_source`++ provenance.

**Comment by RichardBruskiewich** [comment]
"warning.knowledge_graph.edge.attribute.type_id.unknown_prefix": {
      "CHEMBL.COMPOUND:CHEMBL112--biolink:occurs_together_in_literature_with->CHEMBL.COMPOUND:CHEMBL1201558": [
        {
          "attribute_type_id": "EDAM-DATA:2526"
        },
        {
          "attribute_type_id": "EDAM-OPERATION:0226"
        },

**Comment by RichardBruskiewich** [comment]
```yaml
  attribute:
    is_a: named thing
    mixins:
      - ontology class
...
    slots:
      - name                   # 'attribute_name'
      - has attribute type     # 'attribute_type'
      # 'value', 'value_type', 'value_type_name'
      # extracted from either of the next two slots
      - has quantitative value
      - has qualitative value
...
    id_prefixes:
      - EDAM-DATA
      - EDAM-FORMAT
      - EDAM-OPERATION
      - EDAM-TOPIC
 ```

**Comment by RichardBruskiewich** [comment]
`biolink:has_attribute_type`  is defined:

```yaml
  has attribute type:
...
    domain: attribute
    range: ontology class
    multivalued: false
    required: true
...
```
