### ISSUE TITLE
Review how deprecated Biolink Model classes are being detected and reported

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATSTranslator/reasoner-validator#24]
By example, a recent test using the validator gives the following error:

```yaml
SKIPPED (test case S-P-O triple '(CHEBI:3002$biolink:ChemicalSubstance)--[biolink:treats]->(MESH:D001249$biolink:Disease)', since it is not Biolink Model compliant: BLM Version 2.4.4 Error in Input Edge: 'subject' category 'biolink:ChemicalSubstance' is unknown?)
```

In the 2.4.4 model, we see 

```yaml
  chemical substance:
    deprecated: >-
      This class is deprecated in favor of 'small molecule.'
```

The validation is detecting use of the deprecated class as test error. Although this is probably ok, we perhaps still need to review (and possibly adjust) error reporting for deprecated classes.
